# QuizMentor Docker Compose Configuration
# For local development and testing

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: quizmentor-postgres
    environment:
      POSTGRES_DB: quizmentor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - quizmentor-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: quizmentor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quizmentor-network

  # API Server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: quizmentor-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/quizmentor
      REDIS_URL: redis://redis:6379
      API_PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - quizmentor-network
    command: npm run dev

  # Web Application (Next.js)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: quizmentor-web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - quizmentor-network
    command: npm run web

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: quizmentor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api
    networks:
      - quizmentor-network

  # Analytics Service (Optional)
  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    container_name: quizmentor-analytics
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/quizmentor
      REDIS_URL: redis://redis:6379
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
    networks:
      - quizmentor-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  quizmentor-network:
    driver: bridge
