# DigitalOcean App Platform Configuration
name: quizmentor-production
region: nyc
domains:
  - domain: quizmentor.app
    type: PRIMARY

# Frontend Next.js Application
services:
  - name: frontend
    github:
      repo: your-github-username/quizmentor
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    run_command: npm start
    instance_size: basic-xs
    instance_count: 1
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}/api
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_ANON_KEY}

  # API Backend Service
  - name: api
    github:
      repo: your-github-username/quizmentor
      branch: main
      deploy_on_push: true
    source_dir: /api
    dockerfile_path: api/Dockerfile
    instance_size: basic-s
    instance_count: 2
    instance_count_min: 1
    instance_count_max: 5
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
    routes:
      - path: /api
    envs:
      # Database
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      
      # OpenAI
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${OPENAI_API_KEY}
      - key: OPENAI_ORG_ID
        scope: RUN_TIME
        type: SECRET
        value: ${OPENAI_ORG_ID}
      
      # Pinecone Vector DB
      - key: PINECONE_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${PINECONE_API_KEY}
      - key: PINECONE_ENV
        scope: RUN_TIME
        value: us-east-1-aws
      
      # Supabase
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SUPABASE_SERVICE_KEY}
      
      # Feature Flags
      - key: POSTHOG_API_KEY
        scope: RUN_TIME
        value: ${POSTHOG_API_KEY}
      
      # Monitoring
      - key: SENTRY_DSN
        scope: RUN_TIME
        value: ${SENTRY_DSN}

# Background Jobs Worker
workers:
  - name: job-processor
    github:
      repo: your-github-username/quizmentor
      branch: main
    source_dir: /workers
    dockerfile_path: workers/Dockerfile
    instance_size: basic-xs
    instance_count: 1
    run_command: node worker.js
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${OPENAI_API_KEY}

# Managed Databases
databases:
  # PostgreSQL for main data
  - name: db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    
  # Redis for caching and queues
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb
    eviction_policy: allkeys-lru

# Static Assets & Files
static_sites:
  - name: docs
    github:
      repo: your-github-username/quizmentor
      branch: main
      deploy_on_push: true
    source_dir: /docs
    output_dir: /docs/build
    routes:
      - path: /docs

# Alerts & Monitoring
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: CPU_UTILIZATION
    value: 85
    window: FIVE_MINUTES
  - rule: MEM_UTILIZATION
    value: 85
    window: FIVE_MINUTES
  - rule: RESTART_COUNT
    value: 5
    window: THIRTY_MINUTES
