export interface Question {
  id: string;
  question: string;
  options: string[];
  correct: number;
  explanation?: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  description: string;
  questions: Question[];
}

export const quizData: Category[] = [
  {
    id: 'geography',
    name: 'Geography',
    icon: '🌍',
    color: '#3b82f6',
    description: 'Test your knowledge of world geography',
    questions: [
      {
        id: 'geo1',
        question: 'What is the capital of France?',
        options: ['London', 'Berlin', 'Paris', 'Madrid'],
        correct: 2,
        explanation: 'Paris has been the capital of France since 987 AD.',
        difficulty: 'easy',
      },
      {
        id: 'geo2',
        question: 'Which is the largest ocean on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
        correct: 3,
        explanation: 'The Pacific Ocean covers about 165.2 million square kilometers.',
        difficulty: 'easy',
      },
      {
        id: 'geo3',
        question: 'Which country has the longest coastline?',
        options: ['Australia', 'Canada', 'Russia', 'Indonesia'],
        correct: 1,
        explanation: 'Canada has a coastline of 202,080 km, the longest in the world.',
        difficulty: 'medium',
      },
      {
        id: 'geo4',
        question: 'What is the smallest country in the world?',
        options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
        correct: 1,
        explanation: 'Vatican City is only 0.44 square kilometers in area.',
        difficulty: 'medium',
      },
      {
        id: 'geo5',
        question: 'Which river is the longest in the world?',
        options: ['Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River'],
        correct: 1,
        explanation: 'The Nile River extends 6,650 km through northeastern Africa.',
        difficulty: 'medium',
      },
      {
        id: 'geo6',
        question: 'How many countries are in Africa?',
        options: ['48', '54', '52', '56'],
        correct: 1,
        explanation: 'Africa has 54 recognized sovereign states.',
        difficulty: 'hard',
      },
      {
        id: 'geo7',
        question: 'What is the driest place on Earth?',
        options: ['Sahara Desert', 'Atacama Desert', 'Death Valley', 'Antarctica'],
        correct: 1,
        explanation: 'The Atacama Desert in Chile receives less than 1mm of rain per year.',
        difficulty: 'hard',
      },
      {
        id: 'geo8',
        question: 'Which mountain range contains Mount Everest?',
        options: ['Alps', 'Andes', 'Himalayas', 'Rocky Mountains'],
        correct: 2,
        explanation: 'Mount Everest is part of the Himalayan mountain range.',
        difficulty: 'easy',
      },
      {
        id: 'geo9',
        question: 'What percentage of Earth is covered by water?',
        options: ['50%', '60%', '71%', '85%'],
        correct: 2,
        explanation: "Approximately 71% of Earth's surface is covered by water.",
        difficulty: 'medium',
      },
      {
        id: 'geo10',
        question: 'Which country is known as the Land of the Rising Sun?',
        options: ['China', 'Japan', 'Korea', 'Thailand'],
        correct: 1,
        explanation: 'Japan is called "Nippon" in Japanese, meaning "sun origin".',
        difficulty: 'easy',
      },
    ],
  },
  {
    id: 'science',
    name: 'Science',
    icon: '🔬',
    color: '#10b981',
    description: 'Explore the wonders of science',
    questions: [
      {
        id: 'sci1',
        question: 'What is the chemical symbol for gold?',
        options: ['Go', 'Gd', 'Au', 'Ag'],
        correct: 2,
        explanation: 'Au comes from the Latin word for gold, "aurum".',
        difficulty: 'easy',
      },
      {
        id: 'sci2',
        question: 'How many bones are in the adult human body?',
        options: ['186', '206', '226', '246'],
        correct: 1,
        explanation: 'Adults have 206 bones, while babies are born with about 270.',
        difficulty: 'medium',
      },
      {
        id: 'sci3',
        question: 'What is the speed of light in vacuum?',
        options: ['299,792,458 m/s', '300,000,000 m/s', '186,282 miles/s', 'All of the above'],
        correct: 0,
        explanation: 'The speed of light in vacuum is exactly 299,792,458 meters per second.',
        difficulty: 'hard',
      },
      {
        id: 'sci4',
        question: 'Which planet is known as the Red Planet?',
        options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
        correct: 1,
        explanation: 'Mars appears red due to iron oxide (rust) on its surface.',
        difficulty: 'easy',
      },
      {
        id: 'sci5',
        question: 'What is the powerhouse of the cell?',
        options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast'],
        correct: 2,
        explanation: "Mitochondria generate most of the cell's ATP energy.",
        difficulty: 'easy',
      },
      {
        id: 'sci6',
        question: "What is the most abundant gas in Earth's atmosphere?",
        options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
        correct: 2,
        explanation: "Nitrogen makes up about 78% of Earth's atmosphere.",
        difficulty: 'medium',
      },
      {
        id: 'sci7',
        question: 'What is the hardest natural substance on Earth?',
        options: ['Quartz', 'Diamond', 'Titanium', 'Graphene'],
        correct: 1,
        explanation: 'Diamond is the hardest naturally occurring substance.',
        difficulty: 'easy',
      },
      {
        id: 'sci8',
        question: 'How many chambers does a human heart have?',
        options: ['2', '3', '4', '5'],
        correct: 2,
        explanation: 'The human heart has 4 chambers: 2 atria and 2 ventricles.',
        difficulty: 'easy',
      },
      {
        id: 'sci9',
        question: 'What is the smallest unit of matter?',
        options: ['Atom', 'Molecule', 'Quark', 'Electron'],
        correct: 2,
        explanation: 'Quarks are the smallest known particles that make up protons and neutrons.',
        difficulty: 'hard',
      },
      {
        id: 'sci10',
        question: 'What causes tides on Earth?',
        options: ['Wind', "Earth's rotation", "Moon's gravity", 'Ocean currents'],
        correct: 2,
        explanation: "The Moon's gravitational pull causes tidal bulges in Earth's oceans.",
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'history',
    name: 'History',
    icon: '📚',
    color: '#f59e0b',
    description: 'Journey through time and historical events',
    questions: [
      {
        id: 'his1',
        question: 'In which year did World War II end?',
        options: ['1943', '1944', '1945', '1946'],
        correct: 2,
        explanation: 'World War II ended in 1945 with the surrender of Japan.',
        difficulty: 'easy',
      },
      {
        id: 'his2',
        question: 'Who was the first President of the United States?',
        options: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'],
        correct: 1,
        explanation: 'George Washington served from 1789 to 1797.',
        difficulty: 'easy',
      },
      {
        id: 'his3',
        question: 'Which ancient wonder of the world still stands today?',
        options: [
          'Colossus of Rhodes',
          'Great Pyramid of Giza',
          'Hanging Gardens',
          'Lighthouse of Alexandria',
        ],
        correct: 1,
        explanation: 'The Great Pyramid of Giza is the only ancient wonder still standing.',
        difficulty: 'medium',
      },
      {
        id: 'his4',
        question: 'Who painted the Mona Lisa?',
        options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
        correct: 1,
        explanation: 'Leonardo da Vinci painted the Mona Lisa between 1503 and 1519.',
        difficulty: 'easy',
      },
      {
        id: 'his5',
        question: 'Which empire was ruled by Julius Caesar?',
        options: ['Greek Empire', 'Roman Empire', 'Persian Empire', 'Byzantine Empire'],
        correct: 1,
        explanation: 'Julius Caesar was a Roman general and statesman.',
        difficulty: 'easy',
      },
      {
        id: 'his6',
        question: 'When did the Berlin Wall fall?',
        options: ['1987', '1989', '1991', '1993'],
        correct: 1,
        explanation: 'The Berlin Wall fell on November 9, 1989.',
        difficulty: 'medium',
      },
      {
        id: 'his7',
        question: 'Who invented the printing press?',
        options: ['Johannes Gutenberg', 'Leonardo da Vinci', 'Isaac Newton', 'Galileo Galilei'],
        correct: 0,
        explanation: 'Gutenberg invented the movable-type printing press around 1440.',
        difficulty: 'medium',
      },
      {
        id: 'his8',
        question: 'Which year did Christopher Columbus reach the Americas?',
        options: ['1490', '1491', '1492', '1493'],
        correct: 2,
        explanation: 'Columbus reached the Americas on October 12, 1492.',
        difficulty: 'easy',
      },
      {
        id: 'his9',
        question: "How long did the Hundred Years' War actually last?",
        options: ['100 years', '116 years', '99 years', '130 years'],
        correct: 1,
        explanation: "The Hundred Years' War lasted from 1337 to 1453 (116 years).",
        difficulty: 'hard',
      },
      {
        id: 'his10',
        question: 'Who was the first person to walk on the moon?',
        options: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Alan Shepard'],
        correct: 1,
        explanation: 'Neil Armstrong walked on the moon on July 20, 1969.',
        difficulty: 'easy',
      },
    ],
  },
  {
    id: 'art',
    name: 'Art & Culture',
    icon: '🎨',
    color: '#ec4899',
    description: 'Discover art, literature, and cultural heritage',
    questions: [
      {
        id: 'art1',
        question: 'Who painted "The Starry Night"?',
        options: ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dalí'],
        correct: 1,
        explanation: 'Van Gogh painted "The Starry Night" in 1889.',
        difficulty: 'easy',
      },
      {
        id: 'art2',
        question: 'Which Shakespeare play features Romeo and Juliet?',
        options: ['Hamlet', 'Macbeth', 'Romeo and Juliet', 'Othello'],
        correct: 2,
        explanation: "Romeo and Juliet is one of Shakespeare's most famous tragedies.",
        difficulty: 'easy',
      },
      {
        id: 'art3',
        question: 'What type of art is Auguste Rodin famous for?',
        options: ['Painting', 'Sculpture', 'Architecture', 'Photography'],
        correct: 1,
        explanation: 'Rodin was a French sculptor, famous for "The Thinker".',
        difficulty: 'medium',
      },
      {
        id: 'art4',
        question: 'Which museum houses the Mona Lisa?',
        options: ['The Met', 'The Louvre', 'The Uffizi', 'The Prado'],
        correct: 1,
        explanation: 'The Mona Lisa is displayed in the Louvre Museum in Paris.',
        difficulty: 'easy',
      },
      {
        id: 'art5',
        question: 'Who wrote "Pride and Prejudice"?',
        options: ['Charlotte Brontë', 'Jane Austen', 'Emily Dickinson', 'Virginia Woolf'],
        correct: 1,
        explanation: 'Jane Austen published Pride and Prejudice in 1813.',
        difficulty: 'medium',
      },
      {
        id: 'art6',
        question: 'What is the art movement that Picasso co-founded?',
        options: ['Impressionism', 'Surrealism', 'Cubism', 'Expressionism'],
        correct: 2,
        explanation: 'Picasso and Georges Braque developed Cubism around 1907.',
        difficulty: 'medium',
      },
      {
        id: 'art7',
        question: 'Which artist cut off his own ear?',
        options: ['Pablo Picasso', 'Vincent van Gogh', 'Paul Gauguin', 'Henri Matisse'],
        correct: 1,
        explanation: 'Van Gogh cut off part of his ear during a mental breakdown in 1888.',
        difficulty: 'easy',
      },
      {
        id: 'art8',
        question: 'What is haiku?',
        options: ['Japanese poetry', 'Chinese painting', 'Indian dance', 'Korean music'],
        correct: 0,
        explanation: 'Haiku is a traditional form of Japanese poetry.',
        difficulty: 'medium',
      },
      {
        id: 'art9',
        question: 'Who composed "The Four Seasons"?',
        options: ['Mozart', 'Beethoven', 'Vivaldi', 'Bach'],
        correct: 2,
        explanation: 'Antonio Vivaldi composed "The Four Seasons" around 1720.',
        difficulty: 'medium',
      },
      {
        id: 'art10',
        question: 'What does "Renaissance" mean?',
        options: ['Revolution', 'Rebirth', 'Reform', 'Revelation'],
        correct: 1,
        explanation: 'Renaissance means "rebirth" in French.',
        difficulty: 'easy',
      },
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: '🏀',
    color: '#f97316',
    description: 'Test your sports knowledge',
    questions: [
      {
        id: 'spo1',
        question: 'How many players are on a basketball team on the court?',
        options: ['4', '5', '6', '7'],
        correct: 1,
        explanation: 'Basketball is played with 5 players per team on the court.',
        difficulty: 'easy',
      },
      {
        id: 'spo2',
        question: 'In which sport would you perform a slam dunk?',
        options: ['Tennis', 'Basketball', 'Volleyball', 'Baseball'],
        correct: 1,
        explanation: 'A slam dunk is a basketball shot.',
        difficulty: 'easy',
      },
      {
        id: 'spo3',
        question: 'How many rings are on the Olympic flag?',
        options: ['4', '5', '6', '7'],
        correct: 1,
        explanation: 'The Olympic flag has 5 interlocking rings.',
        difficulty: 'easy',
      },
      {
        id: 'spo4',
        question: 'What is the maximum score in 10-pin bowling?',
        options: ['200', '250', '300', '350'],
        correct: 2,
        explanation: 'A perfect game in bowling scores 300 points.',
        difficulty: 'medium',
      },
      {
        id: 'spo5',
        question: 'Which country won the 2018 FIFA World Cup?',
        options: ['Brazil', 'Germany', 'France', 'Spain'],
        correct: 2,
        explanation: 'France won the 2018 FIFA World Cup in Russia.',
        difficulty: 'medium',
      },
      {
        id: 'spo6',
        question: 'How long is a marathon?',
        options: ['26.2 miles', '30 miles', '25 miles', '28 miles'],
        correct: 0,
        explanation: 'A marathon is exactly 26.2 miles or 42.195 kilometers.',
        difficulty: 'medium',
      },
      {
        id: 'spo7',
        question: 'In tennis, what is a score of zero called?',
        options: ['Nil', 'Zero', 'Love', 'Nought'],
        correct: 2,
        explanation: 'In tennis, a score of zero is called "love".',
        difficulty: 'easy',
      },
      {
        id: 'spo8',
        question: 'Which sport is known as "the beautiful game"?',
        options: ['Basketball', 'Soccer/Football', 'Tennis', 'Golf'],
        correct: 1,
        explanation: 'Soccer (football) is often called "the beautiful game".',
        difficulty: 'easy',
      },
      {
        id: 'spo9',
        question: 'How many minutes is a round in professional boxing?',
        options: ['2 minutes', '3 minutes', '4 minutes', '5 minutes'],
        correct: 1,
        explanation: 'Professional boxing rounds last 3 minutes.',
        difficulty: 'medium',
      },
      {
        id: 'spo10',
        question: 'What is the highest possible break in snooker?',
        options: ['137', '147', '155', '167'],
        correct: 1,
        explanation: 'The maximum break in snooker is 147.',
        difficulty: 'hard',
      },
    ],
  },
  {
    id: 'movies',
    name: 'Movies & Entertainment',
    icon: '🎬',
    color: '#8b5cf6',
    description: 'Lights, camera, quiz!',
    questions: [
      {
        id: 'mov1',
        question: 'Which movie won the Oscar for Best Picture in 2020?',
        options: ['1917', 'Joker', 'Parasite', 'Once Upon a Time in Hollywood'],
        correct: 2,
        explanation: 'Parasite was the first non-English film to win Best Picture.',
        difficulty: 'medium',
      },
      {
        id: 'mov2',
        question: 'Who directed the movie "Inception"?',
        options: ['Steven Spielberg', 'Christopher Nolan', 'Martin Scorsese', 'James Cameron'],
        correct: 1,
        explanation: 'Christopher Nolan directed Inception in 2010.',
        difficulty: 'easy',
      },
      {
        id: 'mov3',
        question: 'Which actor played Iron Man in the Marvel Cinematic Universe?',
        options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
        correct: 1,
        explanation: 'Robert Downey Jr. played Tony Stark/Iron Man.',
        difficulty: 'easy',
      },
      {
        id: 'mov4',
        question: 'What is the highest-grossing film of all time (not adjusted for inflation)?',
        options: ['Avengers: Endgame', 'Avatar', 'Titanic', 'Star Wars: The Force Awakens'],
        correct: 1,
        explanation: 'Avatar (2009) is the highest-grossing film with $2.9 billion.',
        difficulty: 'medium',
      },
      {
        id: 'mov5',
        question: 'Which film features the line "May the Force be with you"?',
        options: ['Star Trek', 'Star Wars', 'Guardians of the Galaxy', 'Interstellar'],
        correct: 1,
        explanation: 'This iconic line is from the Star Wars franchise.',
        difficulty: 'easy',
      },
      {
        id: 'mov6',
        question: 'Who played The Joker in "The Dark Knight" (2008)?',
        options: ['Jack Nicholson', 'Heath Ledger', 'Jared Leto', 'Joaquin Phoenix'],
        correct: 1,
        explanation: 'Heath Ledger won a posthumous Oscar for this role.',
        difficulty: 'easy',
      },
      {
        id: 'mov7',
        question: 'Which Pixar movie was the first to be released?',
        options: ['Finding Nemo', 'Toy Story', 'Monsters, Inc.', "A Bug's Life"],
        correct: 1,
        explanation: "Toy Story (1995) was Pixar's first feature film.",
        difficulty: 'medium',
      },
      {
        id: 'mov8',
        question: 'In which movie does Tom Hanks say "Life is like a box of chocolates"?',
        options: ['Cast Away', 'Forrest Gump', 'The Terminal', 'Big'],
        correct: 1,
        explanation: 'This famous quote is from Forrest Gump (1994).',
        difficulty: 'easy',
      },
      {
        id: 'mov9',
        question: 'How many Harry Potter films are there?',
        options: ['6', '7', '8', '9'],
        correct: 2,
        explanation: 'There are 8 Harry Potter films in the main series.',
        difficulty: 'easy',
      },
      {
        id: 'mov10',
        question: 'Which film won the most Oscars (11) alongside Ben-Hur and Titanic?',
        options: [
          'The Godfather',
          'The Lord of the Rings: The Return of the King',
          'West Side Story',
          'Gone with the Wind',
        ],
        correct: 1,
        explanation: 'The Return of the King won all 11 Oscars it was nominated for.',
        difficulty: 'hard',
      },
    ],
  },
  {
    id: 'music',
    name: 'Music',
    icon: '🎵',
    color: '#06b6d4',
    description: 'Test your musical knowledge',
    questions: [
      {
        id: 'mus1',
        question: 'How many strings does a standard guitar have?',
        options: ['4', '5', '6', '7'],
        correct: 2,
        explanation: 'A standard guitar has 6 strings.',
        difficulty: 'easy',
      },
      {
        id: 'mus2',
        question: 'Which band released the album "Abbey Road"?',
        options: ['The Rolling Stones', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'],
        correct: 1,
        explanation: 'The Beatles released Abbey Road in 1969.',
        difficulty: 'easy',
      },
      {
        id: 'mus3',
        question: 'What does "K-pop" stand for?',
        options: ['Korean pop', 'Kingdom pop', 'Kool pop', 'Kinetic pop'],
        correct: 0,
        explanation: 'K-pop stands for Korean popular music.',
        difficulty: 'easy',
      },
      {
        id: 'mus4',
        question: 'Who is known as the "King of Pop"?',
        options: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Madonna'],
        correct: 1,
        explanation: 'Michael Jackson earned the title "King of Pop".',
        difficulty: 'easy',
      },
      {
        id: 'mus5',
        question: 'Which instrument has 88 keys?',
        options: ['Organ', 'Piano', 'Harpsichord', 'Accordion'],
        correct: 1,
        explanation: 'A standard piano has 88 keys (52 white and 36 black).',
        difficulty: 'medium',
      },
      {
        id: 'mus6',
        question: 'What year did MTV first go on the air?',
        options: ['1979', '1981', '1983', '1985'],
        correct: 1,
        explanation: 'MTV launched on August 1, 1981.',
        difficulty: 'hard',
      },
      {
        id: 'mus7',
        question: "Which singer's real name is Stefani Germanotta?",
        options: ['Pink', 'Lady Gaga', 'Katy Perry', 'Sia'],
        correct: 1,
        explanation: 'Lady Gaga was born Stefani Joanne Angelina Germanotta.',
        difficulty: 'medium',
      },
      {
        id: 'mus8',
        question: 'How many notes are in an octave?',
        options: ['7', '8', '12', '13'],
        correct: 2,
        explanation: 'An octave contains 12 semitones (notes).',
        difficulty: 'medium',
      },
      {
        id: 'mus9',
        question: 'Which instrument is Yo-Yo Ma famous for playing?',
        options: ['Violin', 'Cello', 'Piano', 'Flute'],
        correct: 1,
        explanation: 'Yo-Yo Ma is a world-renowned cellist.',
        difficulty: 'medium',
      },
      {
        id: 'mus10',
        question: 'What does "DJ" stand for?',
        options: ['Dance Jockey', 'Disc Jockey', 'Digital Jockey', 'Dynamic Jockey'],
        correct: 1,
        explanation: 'DJ stands for Disc Jockey.',
        difficulty: 'easy',
      },
    ],
  },
  {
    id: 'technology',
    name: 'Technology',
    icon: '💻',
    color: '#6366f1',
    description: 'Navigate the digital world',
    questions: [
      {
        id: 'tech1',
        question: 'What does "WWW" stand for?',
        options: ['World Wide Web', 'World Wide Wifi', 'Web World Wide', 'Wide World Web'],
        correct: 0,
        explanation: 'WWW stands for World Wide Web.',
        difficulty: 'easy',
      },
      {
        id: 'tech2',
        question: 'Who founded Microsoft?',
        options: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos'],
        correct: 1,
        explanation: 'Bill Gates co-founded Microsoft with Paul Allen in 1975.',
        difficulty: 'easy',
      },
      {
        id: 'tech3',
        question: 'What does "AI" stand for in technology?',
        options: [
          'Automated Intelligence',
          'Artificial Intelligence',
          'Advanced Interface',
          'Applied Intelligence',
        ],
        correct: 1,
        explanation: 'AI stands for Artificial Intelligence.',
        difficulty: 'easy',
      },
      {
        id: 'tech4',
        question: 'What year was the iPhone first released?',
        options: ['2005', '2006', '2007', '2008'],
        correct: 2,
        explanation: 'The first iPhone was released on June 29, 2007.',
        difficulty: 'medium',
      },
      {
        id: 'tech5',
        question: 'What is the most used programming language in 2024?',
        options: ['Python', 'JavaScript', 'Java', 'C++'],
        correct: 1,
        explanation: 'JavaScript remains the most widely used programming language.',
        difficulty: 'medium',
      },
      {
        id: 'tech6',
        question: 'How many bits are in a byte?',
        options: ['4', '8', '16', '32'],
        correct: 1,
        explanation: 'A byte consists of 8 bits.',
        difficulty: 'easy',
      },
      {
        id: 'tech7',
        question: 'What does "URL" stand for?',
        options: [
          'Universal Resource Locator',
          'Uniform Resource Locator',
          'United Resource Link',
          'User Resource Locator',
        ],
        correct: 1,
        explanation: 'URL stands for Uniform Resource Locator.',
        difficulty: 'medium',
      },
      {
        id: 'tech8',
        question: 'Which company created the Android operating system?',
        options: ['Apple', 'Microsoft', 'Google', 'Samsung'],
        correct: 2,
        explanation: 'Google acquired Android Inc. in 2005 and developed Android OS.',
        difficulty: 'easy',
      },
      {
        id: 'tech9',
        question: 'What does "RAM" stand for?',
        options: [
          'Random Access Memory',
          'Read Access Memory',
          'Rapid Access Memory',
          'Remote Access Memory',
        ],
        correct: 0,
        explanation: 'RAM stands for Random Access Memory.',
        difficulty: 'easy',
      },
      {
        id: 'tech10',
        question: 'What is the name of the first computer virus?',
        options: ['ILOVEYOU', 'Creeper', 'Morris', 'Brain'],
        correct: 1,
        explanation: 'Creeper, created in 1971, is considered the first computer virus.',
        difficulty: 'hard',
      },
    ],
  },
];

export const getRandomQuestions = (categoryId: string, count: number): Question[] => {
  const category = quizData.find((c) => c.id === categoryId);
  if (!category) return [];

  const shuffled = [...category.questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
};

export const getDailyChallenge = (): Question[] => {
  const allQuestions = quizData.flatMap((c) => c.questions);
  const shuffled = [...allQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 5);
};

export const getQuestionsByDifficulty = (
  categoryId: string,
  difficulty: 'easy' | 'medium' | 'hard',
): Question[] => {
  const category = quizData.find((c) => c.id === categoryId);
  if (!category) return [];

  return category.questions.filter((q) => q.difficulty === difficulty);
};
