# QuizMentor Production Deployment Configuration
# Kubernetes deployment for production environment

apiVersion: v1
kind: Namespace
metadata:
  name: quizmentor-prod

---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: quizmentor-config
  namespace: quizmentor-prod
data:
  NODE_ENV: "production"
  API_PORT: "3001"
  REDIS_URL: "redis://quizmentor-redis:6379"
  ENABLE_ANALYTICS: "true"
  ENABLE_PUSH_NOTIFICATIONS: "true"
  RATE_LIMIT_MAX_REQUESTS: "50"

---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: quizmentor-secrets
  namespace: quizmentor-prod
type: Opaque
stringData:
  SUPABASE_URL: "https://your-project.supabase.co"
  SUPABASE_ANON_KEY: "your-anon-key"
  SUPABASE_SERVICE_ROLE_KEY: "your-service-role-key"
  JWT_SECRET: "your-jwt-secret"
  DATABASE_URL: "postgresql://user:pass@host:5432/db"

---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizmentor-api
  namespace: quizmentor-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quizmentor-api
  template:
    metadata:
      labels:
        app: quizmentor-api
    spec:
      containers:
      - name: api
        image: quizmentor/api:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: quizmentor-config
        - secretRef:
            name: quizmentor-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
# API Service
apiVersion: v1
kind: Service
metadata:
  name: quizmentor-api-service
  namespace: quizmentor-prod
spec:
  selector:
    app: quizmentor-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP

---
# Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizmentor-web
  namespace: quizmentor-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizmentor-web
  template:
    metadata:
      labels:
        app: quizmentor-web
    spec:
      containers:
      - name: web
        image: quizmentor/web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.quizmentor.com"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
# Web Service
apiVersion: v1
kind: Service
metadata:
  name: quizmentor-web-service
  namespace: quizmentor-prod
spec:
  selector:
    app: quizmentor-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizmentor-redis
  namespace: quizmentor-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizmentor-redis
  template:
    metadata:
      labels:
        app: quizmentor-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: quizmentor-redis
  namespace: quizmentor-prod
spec:
  selector:
    app: quizmentor-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP

---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quizmentor-ingress
  namespace: quizmentor-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
  - hosts:
    - quizmentor.com
    - api.quizmentor.com
    secretName: quizmentor-tls
  rules:
  - host: quizmentor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quizmentor-web-service
            port:
              number: 80
  - host: api.quizmentor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quizmentor-api-service
            port:
              number: 80

---
# Horizontal Pod Autoscaler for API
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quizmentor-api-hpa
  namespace: quizmentor-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quizmentor-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
