apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizmentor-gateway
  namespace: quizmentor-app
  labels:
    app: quizmentor-gateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizmentor-gateway
  template:
    metadata:
      labels:
        app: quizmentor-gateway
        version: v1
    spec:
      containers:
        - name: quizmentor-gateway
          image: quizmentor/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: LEARNING_ORCHESTRATOR_URL
              value: "http://learning-orchestrator.quizmentor-app.svc.cluster.local:3010"
            - name: ADAPTIVE_ENGINE_URL
              value: "http://adaptive-engine.quizmentor-app.svc.cluster.local:3011"
            - name: BLOOM_VALIDATOR_URL
              value: "http://bloom-validator.quizmentor-app.svc.cluster.local:3012"
            - name: AUTH_SERVICE_URL
              value: "http://keycloak.devmentor-app.svc.cluster.local:8080"
            - name: CORS_ORIGIN
              value: "*"
            - name: RATE_LIMIT_ENABLED
              value: "true"
            - name: RATE_LIMIT_WINDOW_MS
              value: "60000"
            - name: RATE_LIMIT_MAX_REQUESTS
              value: "100"
            - name: LOG_LEVEL
              value: "info"
            - name: ENABLE_TRACING
              value: "true"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: quizmentor-gateway
  namespace: quizmentor-app
  labels:
    app: quizmentor-gateway
spec:
  selector:
    app: quizmentor-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
