apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloom-validator
  namespace: quizmentor-app
  labels:
    app: bloom-validator
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloom-validator
  template:
    metadata:
      labels:
        app: bloom-validator
        version: v1
    spec:
      containers:
        - name: bloom-validator
          image: quizmentor/bloom-validator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3012
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3012"
            - name: POSTGRES_HOST
              value: "postgresql.quizmentor-data.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "quizmentor"
            - name: REDIS_HOST
              value: "redis.quizmentor-data.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: VALIDATION_THRESHOLD
              value: "0.7"
            - name: COGNITIVE_COMPLEXITY_ENABLED
              value: "true"
            - name: PEDAGOGICAL_ALIGNMENT_CHECK
              value: "true"
            - name: LOG_LEVEL
              value: "info"
            - name: ENABLE_TRACING
              value: "true"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3012
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3012
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: bloom-validator
  namespace: quizmentor-app
  labels:
    app: bloom-validator
spec:
  selector:
    app: bloom-validator
  ports:
    - name: http
      port: 3012
      targetPort: 3012
      protocol: TCP
