apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-orchestrator
  namespace: quizmentor-app
  labels:
    app: learning-orchestrator
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-orchestrator
  template:
    metadata:
      labels:
        app: learning-orchestrator
        version: v1
    spec:
      containers:
        - name: learning-orchestrator
          image: quizmentor/learning-orchestrator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3010
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3010"
            - name: ADAPTIVE_ENGINE_URL
              value: "http://adaptive-engine.quizmentor-app.svc.cluster.local:3011"
            - name: BLOOM_VALIDATOR_URL
              value: "http://bloom-validator.quizmentor-app.svc.cluster.local:3012"
            - name: POSTGRES_HOST
              value: "postgresql.quizmentor-data.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "quizmentor"
            - name: REDIS_HOST
              value: "redis.quizmentor-data.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: QDRANT_HOST
              value: "qdrant.quizmentor-data.svc.cluster.local"
            - name: QDRANT_PORT
              value: "6333"
            - name: LOG_LEVEL
              value: "info"
            - name: ENABLE_TRACING
              value: "true"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3010
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3010
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: learning-orchestrator
  namespace: quizmentor-app
  labels:
    app: learning-orchestrator
spec:
  selector:
    app: learning-orchestrator
  ports:
    - name: http
      port: 3010
      targetPort: 3010
      protocol: TCP
