name: CI

on:
  push:
    branches: [main, staging, dev]
  pull_request:
    branches: [main, staging, dev]
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you running CI manually?"
        required: false
        default: "manual trigger"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npm run prettier:check

      - name: Lint
        run: npm run lint -- --quiet

      - name: Reference integrity
        run: npm run integrity:check
