name: Question Pipeline (Optional)

on:
  pull_request:
    types: [opened, synchronize, edited, reopened, ready_for_review]
  workflow_dispatch: {}

jobs:
  pipeline:
    name: Import → Quality → Curate (if source present)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run pipeline if devmentor source exists
        shell: bash
        run: |
          set -euo pipefail
          if [ -d devmentor/quiz-system ]; then
            echo "Found devmentor/quiz-system. Running import → quality → curate..."
            node scripts/cli-import.js
            node scripts/quality-evaluate.js
            node scripts/curate-quality.js
          else
            echo "Skipping question pipeline (devmentor/quiz-system not found)."
          fi

      - name: Upload curated artifact (if present)
        if: ${{ hashFiles('data/cli_import/curated.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: curated-questions
          path: |
            data/cli_import/curated.json
            data/cli_import/curated.csv
            data/cli_import/quality_report.json
            data/cli_import/questions.json
            data/cli_import/categories.json

